-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  google_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  name text,
  avatar_url text,
  neo_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gmail_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  email text NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['personal'::text, 'college'::text])),
  google_account_id text,
  access_token_encrypted text,
  refresh_token_encrypted text,
  token_expiry timestamp with time zone,
  last_sync_at timestamp with time zone,
  last_history_id text,
  is_connected boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gmail_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  aliases ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'unknown'::text CHECK (status = ANY (ARRAY['not_applied'::text, 'applied'::text, 'registration_open'::text, 'ppt_scheduled'::text, 'ppt_ongoing'::text, 'ppt_completed'::text, 'shortlisted'::text, 'test_scheduled'::text, 'test_ongoing'::text, 'test_completed'::text, 'interview_scheduled'::text, 'interview_ongoing'::text, 'interview_completed'::text, 'selected'::text, 'offer'::text, 'offer_received'::text, 'rejected'::text, 'not_shortlisted'::text, 'rejected_test'::text, 'rejected_interview'::text, 'withdrawn'::text, 'declined'::text, 'unknown'::text])),
  status_source text,
  status_confidence text DEFAULT 'low'::text CHECK (status_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'ai'::text, 'manual'::text])),
  role text,
  ctc text,
  stipend text,
  location text,
  eligibility text,
  branches ARRAY,
  cgpa_requirement text,
  backlog_requirement text,
  registration_deadline timestamp with time zone,
  job_description text,
  manual_override boolean DEFAULT false,
  notes text,
  applied_at timestamp with time zone,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  category text,
  status_source_email_at timestamp with time zone,
  placement_drive_id uuid NOT NULL,
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT applications_placement_drive_id_fkey FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id)
);
CREATE TABLE public.emails (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gmail_account_id uuid NOT NULL,
  user_id uuid NOT NULL,
  gmail_message_id text NOT NULL,
  thread_id text,
  sender text,
  subject text,
  received_at timestamp with time zone,
  body_snippet text,
  classification text CHECK (classification = ANY (ARRAY['registration'::text, 'registration_confirmation'::text, 'application_status'::text, 'withdrawal'::text, 'decline'::text, 'shortlist'::text, 'ppt'::text, 'test'::text, 'interview'::text, 'jd'::text, 'venue_update'::text, 'result'::text, 'general'::text, 'unclassified_placement_notice'::text, 'irrelevant'::text, 'unclassified'::text])),
  is_processed boolean DEFAULT false,
  is_relevant boolean DEFAULT true,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  placement_drive_id uuid,
  assignment_state text DEFAULT 'unassigned'::text,
  assignment_confidence text DEFAULT 'low'::text,
  assignment_source text,
  CONSTRAINT emails_pkey PRIMARY KEY (id),
  CONSTRAINT emails_gmail_account_id_fkey FOREIGN KEY (gmail_account_id) REFERENCES public.gmail_accounts(id),
  CONSTRAINT emails_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT emails_placement_drive_id_fkey FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id)
);
CREATE TABLE public.candidate_matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  email_id uuid,
  neo_id text NOT NULL,
  match_type text NOT NULL CHECK (match_type = ANY (ARRAY['xlsx_cell'::text, 'xlsx_applied_list'::text, 'pdf_text'::text, 'docx_text'::text, 'email_body'::text, 'email_subject'::text])),
  matched_value text,
  match_location text,
  confidence text DEFAULT 'high'::text CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  created_at timestamp with time zone DEFAULT now(),
  placement_drive_id uuid NOT NULL,
  CONSTRAINT candidate_matches_pkey PRIMARY KEY (id),
  CONSTRAINT candidate_matches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT candidate_matches_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id),
  CONSTRAINT candidate_matches_placement_drive_id_fkey FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['registration_deadline'::text, 'ppt'::text, 'online_test'::text, 'coding_test'::text, 'technical_interview'::text, 'hr_interview'::text, 'final_interview'::text, 'result'::text, 'joining_date'::text, 'other'::text])),
  title text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  venue text,
  mode text CHECK (mode = ANY (ARRAY['online'::text, 'offline'::text, 'hybrid'::text, 'unknown'::text])),
  source_email_id uuid,
  confidence text DEFAULT 'high'::text CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'ai'::text])),
  manual_override boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gcal_event_id text,
  placement_drive_id uuid NOT NULL,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT events_source_email_id_fkey FOREIGN KEY (source_email_id) REFERENCES public.emails(id),
  CONSTRAINT events_placement_drive_id_fkey FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['new_company'::text, 'shortlist_match'::text, 'test_scheduled'::text, 'interview_scheduled'::text, 'ppt_scheduled'::text, 'deadline_approaching'::text, 'status_change'::text, 'sync_complete'::text, 'general'::text])),
  title text NOT NULL,
  message text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  body text,
  link text,
  event_id uuid,
  dedupe_key text UNIQUE,
  placement_drive_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT notifications_placement_drive_id_fkey FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notification_preferences (
  user_id uuid NOT NULL,
  browser_push_enabled boolean DEFAULT true,
  in_app_enabled boolean DEFAULT true,
  notify_status_change boolean DEFAULT true,
  notify_shortlist boolean DEFAULT true,
  notify_tests boolean DEFAULT true,
  notify_interviews boolean DEFAULT true,
  notify_ppt boolean DEFAULT true,
  notify_new_jds boolean DEFAULT true,
  notify_reminders boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reminder_event_types ARRAY DEFAULT ARRAY['online_test'::text, 'coding_test'::text, 'technical_interview'::text, 'hr_interview'::text, 'final_interview'::text, 'ppt'::text, 'registration_deadline'::text],
  reminder_lead_time_mins ARRAY DEFAULT ARRAY[1440, 120, 15],
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.drive_resolutions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  drive_number text NOT NULL UNIQUE,
  company_base_name text NOT NULL,
  resolved_role text NOT NULL,
  resolved_company_name text NOT NULL,
  resolved_via text NOT NULL CHECK (resolved_via = ANY (ARRAY['timing_correlation'::text, 'direct_role_text'::text, 'manual_review'::text, 'historical_rule'::text])),
  confidence text NOT NULL DEFAULT 'high'::text CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'needs_review'::text])),
  time_diff_seconds integer,
  candidate_circular_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drive_resolutions_pkey PRIMARY KEY (id),
  CONSTRAINT drive_resolutions_candidate_circular_id_fkey FOREIGN KEY (candidate_circular_id) REFERENCES public.emails(id)
);
CREATE TABLE public.sync_state (
  user_id uuid NOT NULL,
  is_syncing boolean DEFAULT false,
  phase text DEFAULT 'idle'::text,
  account_email text,
  account_type text,
  total_messages integer DEFAULT 0,
  processed_messages integer DEFAULT 0,
  new_emails integer DEFAULT 0,
  new_companies integer DEFAULT 0,
  skipped_duplicates integer DEFAULT 0,
  current_subject text,
  is_initial_sync boolean DEFAULT false,
  current_page_index integer DEFAULT 0,
  total_pages integer DEFAULT 1,
  started_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  last_error text,
  CONSTRAINT sync_state_pkey PRIMARY KEY (user_id),
  CONSTRAINT sync_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.sync_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  gmail_account_id uuid,
  page_index integer NOT NULL,
  message_ids jsonb NOT NULL,
  next_offset integer DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'complete'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_pages_pkey PRIMARY KEY (id),
  CONSTRAINT sync_pages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT sync_pages_gmail_account_id_fkey FOREIGN KEY (gmail_account_id) REFERENCES public.gmail_accounts(id)
);
CREATE TABLE public.feedback_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  user_email text NOT NULL,
  user_name text,
  category text NOT NULL CHECK (category = ANY (ARRAY['bug'::text, 'feature'::text, 'sync_issue'::text, 'general'::text])),
  severity text NOT NULL DEFAULT 'normal'::text CHECK (severity = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text])),
  subject text NOT NULL,
  message text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feedback_reports_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.placement_drives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  drive_number text,
  normalized_drive_number text,
  drive_name text,
  role text,
  category text,
  ctc text,
  stipend text,
  location text,
  eligibility text,
  branches ARRAY,
  cgpa_requirement text,
  backlog_requirement text,
  registration_deadline timestamp with time zone,
  identity_state text NOT NULL DEFAULT 'unassigned'::text CHECK (identity_state = ANY (ARRAY['assigned'::text, 'ambiguous'::text, 'unassigned'::text, 'legacy'::text, 'conflict'::text, 'manually_assigned'::text])),
  identity_confidence text NOT NULL DEFAULT 'low'::text CHECK (identity_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  identity_source text,
  source_email_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT placement_drives_pkey PRIMARY KEY (id),
  CONSTRAINT placement_drives_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT placement_drives_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.email_drive_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  email_id uuid NOT NULL,
  placement_drive_id uuid NOT NULL,
  link_type text NOT NULL DEFAULT 'candidate'::text CHECK (link_type = ANY (ARRAY['primary'::text, 'secondary'::text, 'pooled'::text, 'reference_only'::text, 'ambiguous_candidate'::text])),
  confidence text NOT NULL DEFAULT 'low'::text CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  assignment_source text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_drive_links_pkey PRIMARY KEY (id),
  CONSTRAINT email_drive_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT email_drive_links_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.emails(id),
  CONSTRAINT email_drive_links_drive_id_fkey FOREIGN KEY (placement_drive_id) REFERENCES public.placement_drives(id)
);