'use client';

import { useState, useEffect, useCallback } from 'react';

/**
 * Converts a base64url VAPID public key string to a Uint8Array buffer
 * required by the browser's pushManager.subscribe().
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export function usePushNotifications() {
  const [isSupported, setIsSupported] = useState(false);
  const [permission, setPermission] = useState<NotificationPermission>('default');
  const [isSubscribed, setIsSubscribed] = useState(false);
  const [isChecking, setIsChecking] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Check support and active subscription status
  useEffect(() => {
    if (
      typeof window !== 'undefined' &&
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      'Notification' in window
    ) {
      setIsSupported(true);
      const perm = Notification.permission;
      setPermission(perm);

      navigator.serviceWorker.ready
        .then(async (registration) => {
          try {
            const subscription = await registration.pushManager.getSubscription();
            setIsSubscribed(false);

            // Sync subscription with backend database only if active
            if (subscription) {
              const subJson = subscription.toJSON();
              if (subJson.endpoint && subJson.keys?.p256dh && subJson.keys?.auth) {
                const response = await fetch('/api/notifications/subscribe', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({
                    endpoint: subJson.endpoint,
                    p256dh: subJson.keys.p256dh,
                    auth: subJson.keys.auth,
                    userAgent: navigator.userAgent,
                  }),
                });
                if (!response.ok) throw new Error('This browser subscription could not be saved. Enable notifications again to retry.');
                setIsSubscribed(true);
              }
            }
          } catch (err) {
            console.warn('[Push Hook] Failed to inspect push subscription:', err);
            setError(err instanceof Error ? err.message : 'Unable to verify browser notifications.');
          } finally {
            setIsChecking(false);
          }
        })
        .catch(() => {
          setIsChecking(false);
        });
    } else {
      setIsChecking(false);
    }
  }, []);

  // Register service worker on initial load without requesting notification permission
  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      navigator.serviceWorker
        .register('/sw.js')
        .then((reg) => {
          console.log('[SW] Service Worker registered successfully with scope:', reg.scope);
        })
        .catch((err) => {
          console.error('[SW] Service Worker registration failed:', err);
          setIsChecking(false);
          setError('Unable to register browser notifications. Reload and try again.');
        });
    }
  }, []);

  /**
   * Explicitly requests permission and subscribes to Web Push.
   */
  const subscribeToPush = useCallback(async () => {
    if (!isSupported) {
      setError('Web Push is not supported in this browser.');
      return false;
    }

    const vapidKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
    if (!vapidKey) {
      setError('VAPID public key is missing.');
      return false;
    }

    setLoading(true);
    setError(null);

    try {
      // 1. Request notification permission (user prompt)
      const userPermission = await Notification.requestPermission();
      setPermission(userPermission);

      if (userPermission !== 'granted') {
        setError('Notification permission was denied.');
        setLoading(false);
        return false;
      }

      // 2. Get Service Worker registration
      const registration = await navigator.serviceWorker.ready;

      // 3. Subscribe with PushManager
      const convertedVapidKey = urlBase64ToUint8Array(vapidKey);
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey as unknown as BufferSource,
      });

      const subscriptionJson = subscription.toJSON();

      if (!subscriptionJson.endpoint || !subscriptionJson.keys) {
        throw new Error('Incomplete subscription generated by browser');
      }

      // 4. Save subscription to backend
      const res = await fetch('/api/notifications/subscribe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          endpoint: subscriptionJson.endpoint,
          p256dh: subscriptionJson.keys.p256dh,
          auth: subscriptionJson.keys.auth,
          userAgent: navigator.userAgent,
          enablePush: true,
        }),
      });

      if (!res.ok) {
        throw new Error('Failed to save subscription on server');
      }

      setIsSubscribed(true);
      setLoading(false);
      return true;
    } catch (err: unknown) {
      console.error('[Push Hook] Subscribe error:', err);
      const errMsg = err instanceof Error ? err.message : String(err);
      if (
        errMsg.toLowerCase().includes('push service error') ||
        (err as { name?: string })?.name === 'AbortError'
      ) {
        setError(
          "Push service connection failed. If using Brave Browser, enable 'Use Google services for push messaging' in brave://settings/privacy."
        );
      } else {
        setError(errMsg || 'Subscription failed');
      }
      setLoading(false);
      return false;
    }
  }, [isSupported]);

  /**
   * Unsubscribes from Web Push.
   */
  const unsubscribeFromPush = useCallback(async () => {
    if (!isSupported) return false;

    setLoading(true);
    setError(null);

    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();

      if (subscription) {
        // Remove from backend
        const response = await fetch('/api/notifications/unsubscribe', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ endpoint: subscription.endpoint }),
        });
        if (!response.ok) throw new Error('Failed to remove the subscription on the server');

        // Unsubscribe locally in browser
        await subscription.unsubscribe();
      }

      setIsSubscribed(false);
      setLoading(false);
      return true;
    } catch (err) {
      console.error('[Push Hook] Unsubscribe error:', err);
      setError(err instanceof Error ? err.message : 'Unsubscribe failed');
      setLoading(false);
      return false;
    }
  }, [isSupported]);

  return {
    isSupported,
    permission,
    isSubscribed,
    isChecking,
    loading,
    error,
    subscribeToPush,
    unsubscribeFromPush,
  };
}
